name: egyptianrc
description: Project for Egyptian Red Crescent

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0-317.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.2.1
  flutter_spinkit: ^5.1.0
  photo_view: ^0.14.0
  # web services
  dio: ^4.0.6
  #firebase
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  google_sign_in: ^5.4.2
  firebase_storage: ^11.0.10
  cloud_firestore: ^4.3.1
  firebase_database: ^10.0.9
  firebase_messaging: ^14.2.1
  firebase_analytics: ^10.1.0
  # local files
  permission_handler: ^10.2.0
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11
  path: ^1.8.2
  # images and videos
  image_picker: ^0.8.6+1
  #  chewie: ^1.4.0
  #  camera: ^0.10.3
  # sounds
  flutter_sound: ^9.2.13
  audioplayers: ^3.0.1
  # operation
  google_maps_flutter: ^2.2.3
  google_maps_flutter_web: ^0.4.0+5
  #  google_maps_flutter: ^2.2.2
  #  google_maps_flutter: ^2.2.2
  # google_maps_flutter_android: ^2.4.3
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  equatable: ^2.0.5
  either_dart: ^0.3.0
  connectivity_plus: ^3.0.2
  #styles
  flutter_native_splash: ^2.2.14
  google_fonts: ^3.0.1
  fluttertoast: ^8.1.1
  #widgets
  flutter_svg: ^1.1.6
  pin_code_fields: ^7.3.0
  cached_network_image: ^3.2.3
  avatar_glow: ^2.0.2
  flutter_neumorphic: ^3.2.0
  #additinal
  intl: ^0.17.0
  flutter_vibrate: ^1.3.0
  url_launcher: ^6.1.8
  geolocator: ^9.0.2
  flutter_screenutil: ^5.6.1
  device_preview: ^1.1.0
  material_floating_search_bar: ^0.3.7
  dart_geohash: ^2.0.2
  universal_ui: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
